# Generated by Django 5.2.14 on 2026-05-29 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_feeding_pumping_amount_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='weight',
            name='weight_unit',
            field=models.CharField(blank=True, choices=[('kg', 'kg'), ('lb', 'lb')], default='', max_length=10, verbose_name='Weight unit'),
        ),
    ]
