# Generated by Django 5.2.14 on 2026-05-29 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_weight_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='headcircumference',
            name='unit',
            field=models.CharField(blank=True, choices=[('cm', 'cm'), ('in', 'in')], default='', max_length=10, verbose_name='Unit'),
        ),
        migrations.AddField(
            model_name='height',
            name='unit',
            field=models.CharField(blank=True, choices=[('cm', 'cm'), ('in', 'in')], default='', max_length=10, verbose_name='Unit'),
        ),
    ]
