# Generated by Django 5.2.14 on 2026-05-29 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_height_headcircumference_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='temperature',
            name='temperature_unit',
            field=models.CharField(blank=True, choices=[('c', '°C'), ('f', '°F')], default='', max_length=10, verbose_name='Temperature unit'),
        ),
    ]
