# Generated by Django 5.2.14 on 2026-05-29 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_temperature_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaperchange',
            name='amount_unit',
            field=models.CharField(blank=True, choices=[('g', 'g'), ('oz', 'oz')], default='', max_length=10, verbose_name='Amount unit'),
        ),
    ]
